apiVersion: v1
kind: Service
metadata:
  name: webserver-frontend
  labels:
    service: webserver-frontend
spec:
  type: ClusterIP
  selector:
    app: webserver-frontend
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-frontend
  labels:
    app: webserver-frontend
spec:
  selector:
    matchLabels:
      app: webserver-frontend
  template:
    metadata:
      labels:
        app: webserver-frontend
    spec:
      serviceAccountName: svelte
      containers:
        - name: webserver-frontend
          image: webserver-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svelte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svelte-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-aggregate-to-admin
subjects:
- kind: ServiceAccount
  name: svelte
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svelte-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: svelte
  namespace: default