apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: opensoar
build:
  artifacts:
  - image: webserver-backend
    context: src/webserver/backend/
    docker:
      dockerfile: Dockerfile
  - image: webserver-frontend
    context: src/webserver/frontend/
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command:
              - sh
              - -c
              - kubectl apply -f src/argo/argo-ns.yaml --wait=true
    manifests:
    - src/argo/argo.yaml
    - src/k8s.yaml
    - src/webserver/backend/k8s.yaml
    - src/webserver/frontend/k8s.yaml