services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: opensoar
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: opensoar
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080